language: ruby
cache: bundler
sudo: false
rvm:
  - 2.5
jdk: 'openjdk8'
matrix:
  include:
    - rvm: 2.4

notifications:
  irc: "irc.freenode.org#ldpddev"

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true